version: "3"
services:
  online-shopping-app:
    container_name: online-shopping-container
    image: abdelrahman370/online-shopping
    ports:
      - "3001:3001"
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data
  web:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - online-shopping-app
volumes:
  postgres-db: