version: "3"
services:
  mongo:
    image: mongo
    restart: always
    volumes:
      -   mongo-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
  mongo-express:
      image: mongo-express
      restart: always
      ports:
          - 8081:8081
      environment:
          ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USER}
          ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
          ME_CONFIG_MONGODB_URL: mongodb://${DB_USER}:${DB_PASSWORD}@mongo:27017/
          ME_CONFIG_BASICAUTH: false
      depends_on:
          -   mongo
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  mongo-db:
  postgres-db: